services:
  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    env_file:
      - .env.ci
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    extra_hosts:
      - "127.0.0.1:127.0.0.1"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 1s
      timeout: 5s
      retries: 10

  couch_db:
    image: couchdb:3
    container_name: couch_db
    env_file:
      - .env.ci
    ports:
      - ${COUCHDB_PORT}:5984
    restart: always
    extra_hosts:
      - "127.0.0.1:127.0.0.1"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@${COUCHDB_SERVER}:5984",
        ]
      interval: 1s
      timeout: 5s
      retries: 10

  webdav:
    image: xama/nginx-webdav
    restart: always
    env_file:
      - .env.ci
    ports:
      - ${WEBDAV_PORT}:8081
    extra_hosts:
      - "127.0.0.1:127.0.0.1"
    volumes:
      - ./webdav/webdav:/var/webdav/public
      - ./webdav/tokens:/etc/nginx/tokens
      - ./webdav/nginx.conf:/etc/nginx/nginx.conf

  rest:
    restart: always
    image: ${CI_REGISTRY_IMAGE}/rest_api:${CI_COMMIT_REF_SLUG}
    ports:
      - "${REST_PORT}:5002"
    env_file:
      - .env.ci
    depends_on:
      db:
        condition: service_healthy
      couch_db:
        condition: service_healthy
    links:
      - db
    extra_hosts:
      - "127.0.0.1:127.0.0.1"
    healthcheck:
      test: ["CMD-SHELL", "curl -f POST http://rest:${REST_PORT}/api/health"]
      interval: 1s
      retries: 30
      timeout: 10s

  frontend:
    restart: always
    image: ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_REF_SLUG}
    env_file:
      - .env.ci
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      rest:
        condition: service_healthy
    links:
      - rest
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://frontend:${FRONTEND_PORT}/login"]
      interval: 1s
      retries: 30
      timeout: 10s
    extra_hosts:
      - "127.0.0.1:127.0.0.1"

networks:
  default:
    name: trainmate-network
