FROM python:3.12-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libopencv-dev \
    python3-opencv \
    build-essential \
    libhdf5-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade  -r requirements.txt

COPY . .

CMD flask --app app run --debug -p ${REST_PORT} -h 0.0.0.0 --with-threads
